# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "alignreads"
description: Align FASTQ to reference genome and mark duplicates
keywords:
  - align
  - bwa2
  - sentieon-bwa
  - sort
  - picard
  - MarkDuplicates
  - bam
  - bai
components:
  - bwamem2/mem
  - sentieon/bwamem
  - picard/sortsam
  - picard/markduplicates
  - sentieon/dedup
input:
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
      pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
  - fasta:
      type: file
      description: |
        FASTA file
      pattern: "*.{fasta/fa}"
  - index:
      type: file
      description: BWA genome index files
      pattern: "Directory containing BWA index *.{0132,amb,ann,bwt.2bit.64,pac}"
  - sort_bam:
      type: boolean
      description: use samtools sort (true) or samtools view (false)
      pattern: "true or false"
  - aligner:
      type: string
      description: Aligner to use for alignment
      enum:
        - bwa2
        - sentieon-bwamem
  - skip_dedup:
      type: boolean
      description: Flag to run Picard's MarkDuplicates on aligned Bam
      pattern: "true or false"
output:
  - aligned_bams:
      type: file
      description: Output BAM file containing read alignments
      pattern: "*.{bam}"
  - dupmarked_bams:
      type: file
      description: BAM file with duplicate reads marked/removed and their associated indices
      pattern: "*.{bam/bai}"
  - reports:
      type: file
      description: Duplicate metrics file generated by picard
      pattern: "*.{metrics.txt}"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@idt-slowney"
maintainers:
  - "@idt-slowney"
