---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bam2errorprofile"
description: A module to parse samtools mpileup data and generate an error profile
keywords:
  - samtools
  - mpileup
  - bam
  - errorrate
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.bam"
  - bed:
      type: file
      description: Target bed file
      pattern: "*.bed"
  - fasta:
      type: file
      description: Genome fasta file
      pattern: "*.{fa/fasta/fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - error_rate:
      type: file
      description: Parsed mpileup text file
      pattern: "*_mpileup_error_rate.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@idt-slowney"
maintainers:
  - "@idt-slowney"
