---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "picard_collectsequencingartifactmetrics"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::picard=3.2.0"
