# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "prepreferencegenome"
## TODO nf-core: Add a description of the subworkflow and list keywords
description: Prepare genome files
keywords:
  - index
  - reference
  - fai
  - dict
  - fasta
## TODO nf-core: Add a list of the modules and/or subworkflows used in the subworkflow
components:
  - bwamem2/index
  - samtools/faidx
  - picard/createsequencedictionary
  - sentieon/bwaindex
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - fasta:
      type: file
      description: |
        The input fasta file
        Structure: [ fasta ]
      pattern: "*.{fasta/fa}"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@idt-slowney"
maintainers:
  - "@idt-slowney"
